### ISSUE TITLE
Re-setup Travis CI and Coveralls for the project

### ISSUE THREAD

**Issue by ExcaliburZero** [SUNY-Oswego-MUSE-Project/muse-gestures#12]
Since the repository for the project has been moved to the organization, the Travis CI automated builds and the Coveralls coverage reports need to be re-setup to work with the new location of the repository.

@ECE-Engineer 
Since you are the organization owner, you'll need to set this up. Let me know if you have any questions about how to do it.

**Comment by ECE-Engineer** [comment]
Can I meet up with u tomorrow to go over how to do this?

On Thursday, April 14, 2016, Christopher Wells notifications@github.com
wrote:

> Since the repository for the project has been moved to the organization,
> the Travis CI automated builds and the Coveralls coverage reports need to
> be re-setup to work with the new location of the repository.
> 
> @ECE-Engineer https://github.com/ECE-Engineer
> Since you are the organization owner, you'll need to set this up. Let me
> know if you have any questions about how to do it.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/SUNY-Oswego-MUSE-Project/muse-gestures/issues/12

## 

System.out.println("Sincerely, ");

Kyle D Zeller
Electrical & Computer Engineering Major
Computer Science Minor
SUNY Oswego, 2018
(585) 410-0167
kzeller@oswego.edu

**Comment by ExcaliburZero** [comment]
@ECE-Engineer 
Yep, just let me know where and when you want to meet up. I should be able to meet with you just about any time in the evening.

**Comment by ECE-Engineer** [comment]
Ok

On Thursday, April 14, 2016, Christopher Wells notifications@github.com
wrote:

> @ECE-Engineer https://github.com/ECE-Engineer
> Yep, just let me know where and when you want to meet up. I should be able
> to meet with you just about any time in the evening.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/SUNY-Oswego-MUSE-Project/muse-gestures/issues/12#issuecomment-210235785

## 

System.out.println("Sincerely, ");

Kyle D Zeller
Electrical & Computer Engineering Major
Computer Science Minor
SUNY Oswego, 2018
(585) 410-0167
kzeller@oswego.edu
